# ベースイメージ
FROM node:18-alpine

ENV NODE_ENV=development
ENV WATCHPACK_POLLING=true
ENV CHOKIDAR_USEPOLLING=true
ENV FAST_REFRESH=true

# ワークディレクトリ
WORKDIR /app

# package.jsonとpackage-lock.jsonをコピー
COPY package*.json ./

# 依存関係のインストール
RUN npm install
# RUN npm install lightningcss

# プロジェクトファイルをコピー
COPY . .

# 開発用ポートを公開
EXPOSE 3000

# コンテナ起動時のコマンド
CMD ["npm", "run", "dev"]